/**
 * Comprehensive list of languages spoken in India
 * Includes all 22 scheduled languages and other major languages
 */

export const INDIAN_LANGUAGES = [
  // Scheduled Languages (22 official languages)
  'Assamese',
  'Bengali',
  'Bodo',
  'Dogri',
  'Gujarati',
  'Hindi',
  'Kannada',
  'Kashmiri',
  'Konkani',
  'Maithili',
  'Malayalam',
  'Manipuri (Meitei)',
  'Marathi',
  'Nepali',
  'Odia',
  'Punjabi',
  'Sanskrit',
  'Santali',
  'Sindhi',
  'Tamil',
  'Telugu',
  'Urdu',
  
  // Other Major Languages
  'English',
  'Tulu',
  'Rajasthani',
  'Haryanvi',
  'Awadhi',
  'Bhojpuri',
  'Magahi',
  'Chhattisgarhi',
  'Himachali',
  'Garhwali',
  'Kumaoni',
  'Khasi',
  'Mizo',
  'Nagamese',
  'Sikkimese',
  'Ladakhi',
  'Tibetan',
  'Bhili',
  'Gondi',
  'Kurukh',
  'Santhali',
  'Mundari',
  'Ho',
  'Kui',
  'Kuvi',
  'Kodava',
  'Toda',
  'Badaga',
  'Irula',
  'Paniya',
  'Kurumba',
  'Juang',
  'Sora',
  'Gadaba',
  'Koya',
  'Kolami',
  'Naiki',
  'Parji',
  'Ollari',
  'Pengo',
  'Manda',
  'Konda',
  'Mukha Dora',
  'Kisan',
  'Nihali',
  'Korku',
  'Nahali',
  'Kurux',
  'Malto',
  'Brahui',
  'Gujari',
  'Shina',
  'Balti',
  'Purgi',
  'Zangskari',
  'Changthang',
  'Spiti',
  'Kinnauri',
  'Lahauli',
  'Pahari',
  'Kangri',
  'Mandeali',
  'Sirmauri',
  'Bagri',
  'Shekhawati',
  'Mewati',
  'Dhundhari',
  'Harauti',
  'Marwari',
  'Mewari',
  'Wagdi',
  'Gojri',
  'Kutchi',
  'Beary',
  'Coorgi',
  'Lepcha',
  'Limbu',
  'Rai',
  'Tamang',
  'Gurung',
  'Magar',
  'Newari',
  'Tharu',
  'Angika',
  'Bajjika',
  'Sadan',
] as const;

// Remove duplicates and sort alphabetically
export const UNIQUE_INDIAN_LANGUAGES = Array.from(new Set(INDIAN_LANGUAGES)).sort();

// Get sorted list for dropdown
export function getSortedIndianLanguages(): readonly string[] {
  return UNIQUE_INDIAN_LANGUAGES;
}

